# MISC
default rm_intro = False

# UI
default persistent.rm_ui_color = "#FFFFFF"

# CONFIG
default persistent.rm_execute_mode = "sh"
default persistent.rm_view_mode = "list+"
default persistent.rm_auto_save = False
default persistent.rm_json_timer = 2
default persistent.rm_snark_hack = True
default persistent.rm_engines = {"projects": True, "renpy": True, "unity": True, "godot": True, "rpgm": True, "unreal": True}
default persistent.rm_others = {"pinned": False, "stars_query": False}
default persistent.rm_tags = {
    "ai cg": False,
    "2d": False,
    "3d": False,
    "virtual reality": False,
    "side scroller": False,
    "visual novel": False,
    "text based": False,
    "adventure": False,
    "simulator": False,
    "strategy": False,
    "sandbox": False,
    "fantasy": False,
    "combat": False,
    "horror": False,
    "sci-fi": False,
    "harem": False,
    "humor": False,
    "male protagonist ": False,
    "female protagonist": False,
    "futa protagonist": False,
    "trans protagonist": False,
    "tomgirl": False,
    "femboy": False,
    "asian": False,
    "ebony": False,
    "trans": False,
    "furry": False,
    "slave": False,
    "futa": False,
    "loli": False,
    "trap": False,
    "incest": False,
    "granny": False,
    "mother": False,
    "sister": False,
    "aunt": False,
    "milf": False,
    "dilf": False,
    "gilf": False,
    "animated": False,
    "cosplay": False,
    "transformation": False,
    "sissification": False,
    "bimbofication": False,
    "mind control": False,
    "masturbation": False,
    "humiliation": False,
    "superpowers": False,
    "stripping": False,
    "tentacles": False,
    "urination": False,
    "sex toys": False,
    "spanking": False,
    "hypnosis": False,
    "creampie": False,
    "bukkake": False,
    "trainer": False,
    "ahegao": False,
    "virgin": False,
    "drugs": False,
    "sweat": False,
    "scat": False,
    "spit": False,
    "cum": False,
    "big tits": False,
    "big ass": False,
    "vaginal": False,
    "anal": False,
    "interracial": False,
    "corruption": False,
    "domination": False,
    "voyeurism": False,
    "blackmail": False,
    "group sex": False,
    "gangbang": False,
    "cheating": False,
    "voiced": False,
    "vore": False,
    "netorare": False,
    "netorase": False,
    "netori": False,
    }

define config.save_directory = None